version: '3.8'

services:
  mysql-test:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: testpassword
      MYSQL_DATABASE: test_db
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    tmpfs:
      - /var/lib/mysql:rw,noexec,nosuid,size=1024m

  integration-tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      mysql-test:
        condition: service_healthy
    environment:
      MYSQL_TEST_HOST: mysql-test
      MYSQL_TEST_USER: root
      MYSQL_TEST_PASSWORD: testpassword
      MYSQL_TEST_PORT: 3306
    volumes:
      - .:/app
    working_dir: /app
    command: go test -v ./internal -tags=integration